### PR TITLE
use root licen[cs]e in python

### LINKED ISSUE #51: packaging of license file on pypi
@casperdcl Are we packaging the license file when we upload to pypi?

If we want to get the python package on conda-forge by grabbing it from pypi,
we need to have the license file on pypi.

### PR DESCRIPTION
**Pull request by casperdcl**
Simple symlink.

- fixes #51

/cc @gschramm

### CODE REVIEW

**Comment by casperdcl** [comment]
Art[ie]fact seems to have it correctly in the `*.tar.gz` now (https://github.com/ETSInitiative/PETSIRD/actions/runs/11664690131/artifacts/2140826080)

**Comment by gschramm** [comment]
awesome. let me know once pypi is updated, then I will try to get us on conda-forge.

**Review by KrisThielemans — COMMENTED** [review]
Checking this out on Windows gives me just a normal file containing `../LICENSE.txt`, which is also how it is displayed on GitHub.

This makes me a little bit worried.

Maybe we should just do a plain copy...

**Comment by casperdcl** [comment]
Windows isn't used for building distributions so it doesn't matter.

This is tested & working on GH.

**Comment by KrisThielemans** [comment]
> Windows isn't used for building distributions so it doesn't matter.

true, but if anyone checks out on Windows, it looks like a normal file. I also see https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/59761201#59761201

**Pull request closed without merging**
