### PR TITLE
include LICENSE in deployment

### PR DESCRIPTION
**Pull request by KrisThielemans**
alternative to #53

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@gschramm, this should be fine now. Do you need a tagged version?

**Review by casperdcl — CHANGES_REQUESTED** [review]
This won't work. The build dir will be "dirty", the version will be off and/or the file won't be included afaik.

You need #53 instead.

**Comment by KrisThielemans** [comment]
ah. sorry.

I did check that `LICENSE` is included. As it's the only diff, I can't see why the other things would be wrong?

**Comment by KrisThielemans** [comment]
diff between 0.2.0 and latest source from the Action tab is a bit messy because actual file differences [diff.log](https://github.com/user-attachments/files/17659510/diff.log), but the summary is
```
$ diff -q -r petsird-0.*
Only in petsird-0.1.dev1+g90018e6: LICENSE
Files petsird-0.1.dev1+g90018e6/petsird/version.py and petsird-0.2.0/petsird/version.py differ
Files petsird-0.1.dev1+g90018e6/petsird_analysis.py and petsird-0.2.0/petsird_analysis.py differ
Files petsird-0.1.dev1+g90018e6/petsird.egg-info/PKG-INFO and petsird-0.2.0/petsird.egg-info/PKG-INFO differ
Files petsird-0.1.dev1+g90018e6/petsird.egg-info/SOURCES.txt and petsird-0.2.0/petsird.egg-info/SOURCES.txt differ
Files petsird-0.1.dev1+g90018e6/petsird_plot_scanner.py and petsird-0.2.0/petsird_plot_scanner.py differ
Files petsird-0.1.dev1+g90018e6/PKG-INFO and petsird-0.2.0/PKG-INFO differ
```

**Pull request merged**
