### PR TITLE
Minor fixes to C++ and Python tools

### PR DESCRIPTION
**Pull request by naegelejd**
## Changes in this pull request

Minor but useful fixes to the C++ and Python tools.

## Testing performed

Tested using PETSIRD files containing zero CoincidenceEvents, generated using the GATEROOT converter.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added docstrings/doxygen in line with the guidance in the developer guide
- [x] The code builds and runs on my machine

## Contribution Notes

Please read and adhere to the [contribution guidelines](https://github.com/ETSInitiative/PRDdefinition/blob/master/CONTRIBUTING.md).

Please tick the following: 

 - [x] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in the ETSI software (the Work) under the terms and conditions of the [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0) License.

### CODE REVIEW

**Comment by naegelejd** [comment]
@KrisThielemans I also recommend updating the C++ tools to make them compatible with the Python tools and the updated converters:
1. Change from HDF5 to Binary Reader/Writer
1. Change from reading/writing filename to reading/writing `std::cin` and `std::cout`.

I'm happy to add these changes to this PR if you agree.

**Comment by KrisThielemans** [comment]
Thanks @naegelejd. This looks good, although the `deque` is a bit a horrible work-around, so hopefully we can remove it after yardl is updated :-).




> @KrisThielemans I also recommend updating the C++ tools to make them compatible with the Python tools and the updated converters:
> 1. Change from HDF5 to Binary Reader/Writer

I agree it makes sense to let them default to Binary, but I wouldn't cut out the HDF5 code. There's an `#ifdef` already, but maybe you can add a CMake option `USE_HDF5`? (defaulting to `OFF`)

> 2. Change from reading/writing filename to reading/writing `std::cin` and `std::cout`.

Ok for me.
>

**Comment by KrisThielemans** [comment]
Could you please tick the box on the Apache 2 license? We might need to do some more work on that if contributions become more substantial.

**Comment by KrisThielemans** [comment]
Does this fix work? I thought it's a check in the destructor.

I also see some white-space reformatting. What are you using? I tried to use `black`, but might have forgotten. Obviously best to install pre-commit etc for those things.

**Comment by naegelejd** [comment]
I changed `petsird_plot_scanner.py` to ignore TimeBlocks in a much cleaner fashion.

The HDF5 Reader/Writer is not compatible with `std::cin`/`std::cout` (because HDF5 is not designed for streaming), so it doesn't make sense then to change the tools to operate on `stdin`/`stdout` (yet). In MRD, we have separate tools for binary (streams or filenames) vs. HDF5 (filename only).

**Comment by KrisThielemans** [comment]
Referencing https://github.com/microsoft/yardl/issues/183 here for completeness.

**Pull request merged**
